### PR TITLE
Fix #3 - Show command usage for unknown options and exit

### LINKED ISSUE #3: Show command usage when an unknown option is supplied
I think that it would be useful for the command usage to be printed when an unknown option is supplied, instead of ignoring unknown options.

### PR DESCRIPTION
**Pull request by r0b0tbuilder**
When an unknown option is supplied, exit and print command usage.  This could help users who are not famillar with the vipe script.

### CODE REVIEW

**Comment by juliangruber** [comment]
this would also print the message if no option is provided

**Comment by r0b0tbuilder** [comment]
Yes, it would - that is how the else block works.   Is there anything I could do to improve this small change?

**Comment by juliangruber** [comment]
well you need to check if `$1` exists but is neither `-h` or `-V`

**Comment by r0b0tbuilder** [comment]
I fixed that in my latest commit.

**Comment by juliangruber** [comment]
this still doesn't work, if you run

```bash
$ ./vipe.sh
```

It should open an editor, but in your branch it's printing usage instructions instead.

**Comment by r0b0tbuilder** [comment]
I messed up there.  It should be fixed in the last commit.

**Comment by r0b0tbuilder** [comment]
Do my changes look good?

**Comment by juliangruber** [comment]
great! made this a 0.1.0

**Comment by r0b0tbuilder** [comment]
:+1:

**Pull request merged**
